# Generated by Django 4.0.6 on 2022-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastNews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sumamry', models.TextField()),
                ('date_published', models.IntegerField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
