# Generated by Django 4.0.6 on 2022-07-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npm_crawler', '0003_alter_lastnews_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnews',
            name='date_published',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
