# Generated by Django 4.0.6 on 2022-07-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npm_crawler', '0005_alter_lastnews_date_published_alter_lastnews_sumamry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnews',
            name='date_published',
            field=models.CharField(max_length=100),
        ),
    ]
